"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class lcm_vel_cmd(object):

    __slots__ = ["state", "turn", "vx", "vy", "vz", "vw"]

    __typenames__ = ["int64_t", "int64_t", "float", "float", "float", "float"]

    __dimensions__ = [None, None, None, None, None, None]

    def __init__(self):
        self.state = 0
        """ LCM Type: int64_t """
        self.turn = 0
        """ LCM Type: int64_t """
        self.vx = 0.0
        """ LCM Type: float """
        self.vy = 0.0
        """ LCM Type: float """
        self.vz = 0.0
        """ LCM Type: float """
        self.vw = 0.0
        """ LCM Type: float """

    def encode(self):
        buf = BytesIO()
        buf.write(lcm_vel_cmd._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qqffff", self.state, self.turn, self.vx, self.vy, self.vz, self.vw))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcm_vel_cmd._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcm_vel_cmd._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lcm_vel_cmd()
        self.state, self.turn, self.vx, self.vy, self.vz, self.vw = struct.unpack(">qqffff", buf.read(32))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lcm_vel_cmd in parents: return 0
        tmphash = (0xc2e3b0685369daa9) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lcm_vel_cmd._packed_fingerprint is None:
            lcm_vel_cmd._packed_fingerprint = struct.pack(">Q", lcm_vel_cmd._get_hash_recursive([]))
        return lcm_vel_cmd._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcm_vel_cmd._get_packed_fingerprint())[0]

